services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9226:9200'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=recommendation_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5433:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9098
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - '9098:9098'
    depends_on:
      - zookeeper