services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9226:9200'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=recommendation_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5433:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    depends_on:
      - zookeeper
    ports:
      - '9098:9098'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9098
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  recommendation-service:
    build: .
    ports:
      - "8026:8026"
    depends_on:
      - elasticsearch
      - redis
      - kafka
      - postgres

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
    environment:
      - BASE_URL=http://recommendation-service:8026
    # На скрине твой файл в папке k6 называется load-test.js
    entrypoint: ["k6", "run", "/scripts/load-test.js"]
    depends_on:
      - recommendation-service